language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

install:
- dotnet restore

script:
 - dotnet build
 - dotnet test CoreZipCode.Tests/CoreZipCode.Tests.csproj

branches:
  only:
  - master
  - develop

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x .deploy/deploy.sh && .deploy/deploy.sh $NUGET_API_KEY
  on:
    branch: master